// Generates src/environments/environment.prod.ts at build time from the
// API_URL environment variable. Set API_URL in Vercel (or your shell) so the
// backend URL lives in config, not in source — change it without editing code.
const fs = require('fs');
const path = require('path');

// Use API_URL when set (e.g. on Vercel); otherwise fall back to the deployed
// backend so a build without the env var still points at production, not localhost.
const DEFAULT_API_URL = 'https://vendormanagement-qwzydmup.b4a.run';
const rawUrl = process.env.API_URL || DEFAULT_API_URL;
// Ensure exactly one trailing slash (the app joins paths onto apiUrl).
const apiUrl = rawUrl.replace(/\/+$/, '') + '/';

const content = `// AUTO-GENERATED by set-env.js at build time — do not edit by hand.
// To change the backend URL, set the API_URL env var (e.g. in Vercel) and redeploy.
export const environment = {
  production: true,
  apiUrl: '${apiUrl}',
};
`;

const target = path.join(__dirname, 'src', 'environments', 'environment.prod.ts');
fs.writeFileSync(target, content);
console.log(`[set-env] wrote apiUrl=${apiUrl} -> ${target}`);
